// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.web;

import ca.gc.hc.mds.domain.DrugStandard;
import ca.gc.hc.mds.web.DrugStandardController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect DrugStandardController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String DrugStandardController.create(@Valid DrugStandard drugStandard, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, drugStandard);
            return "maintenance/codetable/drugstandard/create";
        }
        uiModel.asMap().clear();
        drugStandard.persist();
        return "redirect:/maintenance/codetable/drugstandard/" + encodeUrlPathSegment(drugStandard.getDrugstandardCd().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String DrugStandardController.createForm(Model uiModel) {
        populateEditForm(uiModel, new DrugStandard());
        return "maintenance/codetable/drugstandard/create";
    }
    
    @RequestMapping(value = "/{drugstandardCd}", produces = "text/html")
    public String DrugStandardController.show(@PathVariable("drugstandardCd") String drugstandardCd, Model uiModel) {
        uiModel.addAttribute("drugstandard", DrugStandard.findDrugStandard(drugstandardCd));
        uiModel.addAttribute("itemId", drugstandardCd);
        return "maintenance/codetable/drugstandard/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String DrugStandardController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("drugstandards", DrugStandard.findDrugStandardEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) DrugStandard.countDrugStandards() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("drugstandards", DrugStandard.findAllDrugStandards(sortFieldName, sortOrder));
        }
        return "maintenance/codetable/drugstandard/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String DrugStandardController.update(@Valid DrugStandard drugStandard, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, drugStandard);
            return "maintenance/codetable/drugstandard/update";
        }
        uiModel.asMap().clear();
        drugStandard.merge();
        return "redirect:/maintenance/codetable/drugstandard/" + encodeUrlPathSegment(drugStandard.getDrugstandardCd().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{drugstandardCd}", params = "form", produces = "text/html")
    public String DrugStandardController.updateForm(@PathVariable("drugstandardCd") String drugstandardCd, Model uiModel) {
        populateEditForm(uiModel, DrugStandard.findDrugStandard(drugstandardCd));
        return "maintenance/codetable/drugstandard/update";
    }
    
    @RequestMapping(value = "/{drugstandardCd}", method = RequestMethod.DELETE, produces = "text/html")
    public String DrugStandardController.delete(@PathVariable("drugstandardCd") String drugstandardCd, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        DrugStandard drugStandard = DrugStandard.findDrugStandard(drugstandardCd);
        drugStandard.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/maintenance/codetable/drugstandard";
    }
    
    void DrugStandardController.populateEditForm(Model uiModel, DrugStandard drugStandard) {
        uiModel.addAttribute("drugStandard", drugStandard);
    }
    
    String DrugStandardController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
