// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.AmendmentReason;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AmendmentReason_Roo_Configurable {
    
    declare @type: AmendmentReason: @Configurable;
    
}
