// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.Company;
import java.io.Serializable;

privileged aspect Company_Roo_Serializable {
    
    declare parents: Company implements Serializable;
    
    private static final long Company.serialVersionUID = 1L;
    
}
