// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.CountryRegionTabPK;
import java.io.Serializable;

privileged aspect CountryRegionTabPK_Roo_Serializable {
    
    declare parents: CountryRegionTabPK implements Serializable;
    
}
