// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.DeviceDrugsPK;
import java.io.Serializable;

privileged aspect DeviceDrugsPK_Roo_Serializable {
    
    declare parents: DeviceDrugsPK implements Serializable;
    
    private static final long DeviceDrugsPK.serialVersionUID = 1L;
    
}
