// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.DrugTab;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

privileged aspect DrugTab_Roo_Equals {
    
    public boolean DrugTab.equals(Object obj) {
        if (!(obj instanceof DrugTab)) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        DrugTab rhs = (DrugTab) obj;
        return new EqualsBuilder().append(descENG, rhs.descENG).append(descFR, rhs.descFR).append(drugID, rhs.drugID).isEquals();
    }
    
    public int DrugTab.hashCode() {
        return new HashCodeBuilder().append(descENG).append(descFR).append(drugID).toHashCode();
    }
    
}
