// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.DrugStandard;

privileged aspect DrugStandard_Roo_JavaBean {
    
    public String DrugStandard.getDrugstandardCd() {
        return this.drugstandardCd;
    }
    
    public void DrugStandard.setDrugstandardCd(String drugstandardCd) {
        this.drugstandardCd = drugstandardCd;
    }
    
    public String DrugStandard.getDrugstandardDesc() {
        return this.drugstandardDesc;
    }
    
    public void DrugStandard.setDrugstandardDesc(String drugstandardDesc) {
        this.drugstandardDesc = drugstandardDesc;
    }
    
}
