// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.DrugTab;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect DrugTab_Roo_Jpa_Entity {
    
    declare @type: DrugTab: @Entity;
    
    declare @type: DrugTab: @Table(schema = "MDSDB", name = "DRUG_TAB");
    
}
