// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.ManufacturersPK;
import java.io.Serializable;

privileged aspect ManufacturersPK_Roo_Serializable {
    
    declare parents: ManufacturersPK implements Serializable;
    
    private static final long ManufacturersPK.serialVersionUID = 1L;
    
}
