// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.RenAuthCompanyPK;

privileged aspect RenAuthCompanyPK_Roo_Serializable {
    
    private static final long RenAuthCompanyPK.serialVersionUID = 1L;
    
}
