// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ca.gc.hc.mds.domain;

import ca.gc.hc.mds.domain.SitesPK;
import java.io.Serializable;

privileged aspect SitesPK_Roo_Serializable {
    
    declare parents: SitesPK implements Serializable;
    
    private static final long SitesPK.serialVersionUID = 1L;
    
}
